language: csharp
dist: trusty
sudo: required
dotnet: 1.0.1
mono: none

solution: TorrentCore.sln

script:
  - dotnet restore src/TorrentCore.Test/TorrentCore.Test.csproj
  - dotnet test src/TorrentCore.Test/TorrentCore.Test.csproj
