language: csharp
dist: trusty
sudo: required
dotnet: 1.0.1
mono: none

solution: TorrentCore.sln

script:
  - dotnet restore TorrentCore.sln
  - dotnet build TorrentCore.sln
  - dotnet test TorrentCore.Test/TorrentCore.Test.csproj
