language: csharp
dist: xenial
dotnet: 2.2
mono: none

solution: TorrentCore.sln

script:
  - dotnet restore TorrentCore.sln
  - dotnet build TorrentCore.sln
  - dotnet test TorrentCore.Test/TorrentCore.Test.csproj
