name: CI
on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required for nbgv
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install aria2
      run: sudo apt-get install aria2
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --no-build -c Release
    - name: Functional Tests
      run: dotnet test --no-restore --no-build -c Release --filter "TestCategory=Functional" -- NUnit.ExplicitMode=Relaxed
